name: Build Nix-Shell Docker

runs:
  using: composite
    steps:
    - id: increment-version
      uses: ymeadows/github-actions-public/tag-next-version@v0
      with:
        prefix: v

    - name: Prepare Nix
      env:
        path_nixpkgs: .config/nixpkgs
        path_confignix: $path_nixpkgs/config.nix
      shell: bash
      run: |
        mkdir -p ~/.config/nixpkgs
        echo "{ allowUnfree = true; }" > ~/.config/nixpkgs/config.nix

    - name: Install Nix
      env:
        USER: runner
      uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup Cachix
      uses: cachix/cachix-action@v10
      with:
        name: ymeadows-build-tools
        extraPullNames: nix-community

    - name: Export nix-shell
      shell: bash
      run: nix-shell --run 'env' | grep -v '\$out' | grep '=' | tee -a $GITHUB_ENV

    - name: Build and Scan
      run: |
        set -x
        nix build
        gzip --decompress --stdout $(readlink result) > image.tar
        trivy image --ignore-unfixed --severity CRITICAL,HIGH --input image.tar
