version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "YM-293"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "pip"
    directory: "/.github/actions/derive-docker-name"
    commit-message:
      prefix: "YM-293"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "America/Los_Angeles"
