name: "Docker: Build And Push"
description: Builds and pushes a docker image to our repos, under multiple tags
inputs:
  version:
    description: The version to be built
    required: true
  image-name:
    description: The base image name to use; defaults to repo name
    required: false
  prefix:
    description: Any prefix of the version (e.g. 'v')
    required: false
  suppress-pull:
    description: >
      Some processes are incompatible with pulling all images.
      Rarely, then, we can prevent that happening.
    required: false
    default: false
  suppress-release:
    description: >
      By default, this action cuts a release with the build log.
      Some consumers may prefer to cut their own releases,
      it which case, set this to true
    required: false
    default: false


runs:
  using: composite

  steps:
  - name: Compute Docker Values
    shell: bash
    run: |
      DOCKER_IMAGE_NAME=${{ inputs.image-name }}
      [ -z "$DOCKER_IMAGE_NAME" ] && DOCKER_IMAGE_NAME=$(echo "${{ github.repository }}" | sed 's#${{ github.repository_owner }}/##')
      echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV

  - name: Build Release Image
    shell: bash
    run: > # folded string
      docker build --tag localbuild ${{ (!inputs.suppress-pull && '--pull') || '' }}
      --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}"
      --label "org.opencontainers.image.version=${{ inputs.version }}"
      --label "org.opencontainers.image.revision=${{ env.REV }}"
      .
      | tee BUILDLOG.txt

      docker save localbuild -o scanme.tar # trouble loading local images

  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@0.11.0
    with:
      input: scanme.tar
      format: 'table'
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'

  - name: Push Docker Archive
    uses: ymeadows/github-actions-public/push-archive@test-251224
    with:
      image-name: ${{env.DOCKER_IMAGE_NAME}}
      version-tag: ${{inputs.version}}
      image-source: docker:localbuild

  - name: Create Release
    if: ${{ !inputs.suppress-release }}
    uses: softprops/action-gh-release@v1
    with:
      body_path: BUILDLOG.txt
      tag_name: ${{ inputs.version }}
