name: "Ephemeral GCE GitHub self-hosted runner"
description: >-
  Creates ephemeral GCE based GitHub Action self-hosted runner.
  It uses startup script to bootstrap the VM.
author: Rafal Wojdyla and Judson Lester
inputs:
  project:
    description: The GCP project to target
    required: false
    default: t0-prod
  project_id_number:
    description: The GCP project id to target
    required: true
  command:
    description: "`start` or `stop` of the runner"
    default: start
    required: true
  token:
    description: >-
      GitHub auth token, needs `repo`/`public_repo` scope: https://docs.github.com/en/rest/reference/actions#self-hosted-runners.
    required: true
  runner_ver:
    description: Version of the GitHub Runner, modified by step:highest-runner-version
    default: "2.298.2"
    required: true
  runner_label:
    description: Extra label to add for the Runner
    required: false
  machine_zone:
    description: GCE zone
    default: "us-west1-b"
    required: true
  machine_type:
    description: GCE machine type; https://cloud.google.com/compute/docs/machine-types
    default: "n1-standard-4"
    required: true
  subnet:
    description: GCP subnet to attach the VM to
    required: true
  external_network:
    description: GCP NIC configuration
    required: false
    default: false
  disk_size:
    description: VM disk size.
    required: false
  runner_service_account:
    description: Service account of the VM, defaults to default compute service account.
    required: false
  image_project:
    description: >
      The Google Cloud project against which all image and image family
      references will be resolved.
    required: false
  image:
    description: Specifies the name of the image that the disk will be initialized with.
    required: false
  image_family:
    description: The image family for the operating system that the boot disk will be initialized with.
    required: false
  preemptible:
    description: Use GCE preemptible VM instance; https://cloud.google.com/compute/docs/instances/preemptible
    default: false
    required: true
  scopes:
    description: Scopes granted to the VM, defaults to full access (cloud-platform).
    default: cloud-platform
    required: true
  shutdown_timeout:
    description: "Grace period for the `stop` command, in seconds."
    default: 30
    required: true
  actions_preinstalled:
    description: "Whether the GitHub actions have already been installed at `/actions-runner`."
    default: false
    required: true
  startup_prequel:
    description: "Script to set up runner prior to common configuration"
    required: false
outputs:
  label:
    description: >-
      Unique runner label. This label can be used to request a specific
      runner for the workflow job.
    value: ${{ steps.gce-github-runner-script.outputs.label }}
runs:
  using: "composite"
  steps:
    - name: Authenticate with GCP
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: "projects/${{inputs.project_id_number}}/locations/global/workloadIdentityPools/github/providers/github-provider"
        service_account: "github-actions-runner-starter@${{inputs.project}}.iam.gserviceaccount.com"
    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v0
    - id: compose-version-candidates
      shell: bash
      run: |
        echo "2.298.2" > candidate-versions
        echo ${{ inputs.runner_ver }} >> candidate-versions
    - id: highest-runner-version
      uses: ymeadows/versiontool@v1
      with:
        version: candidate-versions
        operation: highest
    - id: gce-github-runner-script
      env:
        command: ${{ inputs.command }}
        token: ${{ inputs.token }}
        project_id: ${{ inputs.project }}
        runner_ver: ${{ steps.highest-runner-version.outputs.result }}
        runner_label: ${{ inputs.runner_label }}
        machine_zone: ${{ inputs.machine_zone }}
        machine_type: ${{ inputs.machine_type }}
        subnet: ${{ inputs.subnet }}
        external_network: ${{ inputs.external_network }}
        disk_size: ${{ inputs.disk_size }}
        scopes: ${{ inputs.scopes }}
        shutdown_timeout: ${{ inputs.shutdown_timeout }}
        runner_service_account: ${{ inputs.runner_service_account }}
        image_project: ${{ inputs.image_project }}
        image: ${{ inputs.image }}
        image_family: ${{ inputs.image_family }}
        preemptible: ${{ inputs.preemptible }}
        actions_preinstalled: ${{ inputs.actions_preinstalled }}
        startup_prequel: ${{inputs.startup_prequel}}
      run: >
        ${{ github.action_path }}/action.sh
      shell: bash
