name: 'Append Steps CVE Ignore List'
author: 'Adam Rich'
description: 'Append the list of CVEs to ignore for steps in the Trivy scan to .trivyignore.'
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'shield'
  color: 'green'
