name: "Update Cluster Version"
description: >-
  Triggers an action in tier0-cluster to update a named service's version
author: JDL
inputs:
  REPO_DISPATCH_CLUSTER:
    description: "A PAT to do the repo-dispatch - use ${{secrets.REPO_DISPATCH_CLUSTER}}"
    required: true
    type: string
  service:
    description: "The service to update"
    required: true
    type: string
  version:
    description: "The new version to deploy"
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: peter-evans/repository-dispatch@v2
    with:
      token: ${{inputs.REPO_DISPATCH_CLUSTER}}
      repository: ymeadows/tier0-cluster
      event-type: update-version
      client-payload: '{"service":"${{inputs.service}}", "version":"${{inputs.version}}"}'
