name: Push Docker Archive

inputs:
  image-name:
    description: The base image name to push to
    required: false
  version-tag:
    description: The version to push
    required: true
  prefix:
    description: Any prefix on the version
    default: v

runs:
  using: composite
  steps:
  - id: cut-version
    uses: ymeadows/github-actions-public/lib/rolling-versions@v0
    with:
      version: ${{ inputs.version-tag }}
      prefix: ${{ inputs.prefix }}

  - name: Compute Docker Image Name
    shell: bash
    run: |
      [ -z "$DOCKER_IMAGE_NAME" ] && $DOCKER_IMAGE_NAME="${{ inputs.image-name }}"
      [ -z "$DOCKER_IMAGE_NAME" ] && $DOCKER_IMAGE_NAME=$(echo "${{ github.repository }}" | sed 's#${{ github.repository_owner }}/##')
      echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV
      echo "MAJ=${{steps.cut-version.outputs.major}}" >> $GITHUB_ENV
      echo "MIN=${{steps.cut-version.outputs.major-minor}}" >> $GITHUB_ENV

  - uses: "ymeadows/github-actions-public/lib/setup-gcr@v0"
    with:
      project: t0-qa-282516
      project_id_number: "945001042473"

  - name: Push to QA
    shell: bash
    run: |
      skopeo --insecure-policy copy docker-archive:./result docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{inputs.version-tag}}
      skopeo --insecure-policy copy docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:latest
      skopeo --insecure-policy copy docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:$MIN
      skopeo --insecure-policy copy docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:$MAJ

  - uses: ymeadows/github-actions-public/lib/setup-gcr@v0
    with:
      project: t0-saas
      project_id_number: "991545446866"
  - name: Push to Demo
    shell: bash
    run: |
      skopeo --insecure-policy copy docker-archive:./result docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{inputs.version-tag}}
      skopeo --insecure-policy copy docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:latest
      skopeo --insecure-policy copy docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:$MIN
      skopeo --insecure-policy copy docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:$MAJ

  - uses: ymeadows/github-actions-public/lib/setup-gcr@v0
    with:
      project: t0-prod
      project_id_number: "47742085387"
  - name: Push to Prod
    shell: bash
    run: |
      skopeo --insecure-policy copy docker-archive:./result docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{inputs.version-tag}}
      skopeo --insecure-policy copy docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:latest
      skopeo --insecure-policy copy docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:$MIN
      skopeo --insecure-policy copy docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{inputs.version-tag}} docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:$MAJ
