name: Push Docker Archive

inputs:
  image-name:
    type: string
    optional: true

runs:
  using: composite
    - name: Compute Docker Image Name
      shell: bash
      run: |
        [ -z "$DOCKER_IMAGE_NAME" ] && $DOCKER_IMAGE_NAME=${{ inputs.image-name }}
        [ -z "$DOCKER_IMAGE_NAME" ] && $DOCKER_IMAGE_NAME=$(echo "${{ github.repository }}" | sed 's#${{ github.repository_owner }}/##')
        echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV

    - uses: "ymeadows/github-actions-public/lib/setup-gcr@v0"
      with:
        project: t0-qa-282516
        project_id_number: "945001042473"

    - name: Push to QA
      run: |
        skopeo --insecure-policy copy docker-archive:./result docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}}
        skopeo --insecure-policy copy docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:latest
        skopeo --insecure-policy copy docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-min}}
        skopeo --insecure-policy copy docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-qa-282516/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-maj}}

    - uses: ymeadows/github-actions-public/lib/setup-gcr@v0
      with:
        project: t0-saas
        project_id_number: "991545446866"
    - name: Push to Demo
      run: |
        skopeo --insecure-policy copy docker-archive:./result docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}}
        skopeo --insecure-policy copy docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:latest
        skopeo --insecure-policy copy docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-min}}
        skopeo --insecure-policy copy docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-saas/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-maj}}

    - uses: ymeadows/github-actions-public/lib/setup-gcr@v0
      with:
        project: t0-prod
        project_id_number: "47742085387"
    - name: Push to Prod
      run: |
        skopeo --insecure-policy copy docker-archive:./result docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}}
        skopeo --insecure-policy copy docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:latest
        skopeo --insecure-policy copy docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-min}}
        skopeo --insecure-policy copy docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-tag}} docker://gcr.io/t0-prod/$DOCKER_IMAGE_NAME:${{steps.increment-version.outputs.new-maj}}
