name: Push Docker Archive

inputs:
  image-name:
    description: The base image name to push to
    required: false
  version-tag:
    description: The version to push
    required: true
  prefix:
    description: Any prefix on the version
    default: v

runs:
  using: composite
  steps:
  - uses: ymeadows/github-actions-public/push-archive-to-registry@v0
    with:
      image-name: inputs.image-name
      version-tag: inputs.version-tag
      prefix: inputs.prefix
      project: t0-qa-282516
      project_id_number: "945001042473"
      registry: gcr.io/t0-qa-282516
  - uses: ymeadows/github-actions-public/push-archive-to-registry@v0
    with:
      image-name: inputs.image-name
      version-tag: inputs.version-tag
      prefix: inputs.prefix
      project: t0-prod
      project_id_number: "47742085387"
      registry: gcr.io/t0-prod
