name: Scan For Vulnerabilities
description: Runs Trivy scanner against a built image
inputs:
  image-name:
    description: The base image name to use; defaults to repo name
    required: false
  gcp-project:
    description: The GCP project to target
    required: false
    default: t0-qa-282516
  gcp-project-id:
    description: The ID number of the GCP project
    required: false
    default: "945001042473"
  trivyignores:
    description: Used to control Trivy scans
    required: false
    default: ""

runs:
  using: composite
  steps:
  - name: Compute Docker Values
    shell: bash
    run: |
      DOCKER_IMAGE_NAME=${{ inputs.image-name }}
      [ -z "$DOCKER_IMAGE_NAME"] && DOCKER_IMAGE_NAME=$(echo "${{ github.repository }}" | sed 's#${{ github.repository_owner }}/##')
      DOCKER_FULL_NAME=gcr.io/${{inputs.gcp-project}}/$DOCKER_IMAGE_NAME:latest
      echo "DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME" >> $GITHUB_ENV
      echo "DOCKER_FULL_NAME=$DOCKER_FULL_NAME" >> $GITHUB_ENV

  - uses: ymeadows/github-actions-public/lib/setup-gcr@v0
    with:
      project: ${{ inputs.gcp-project }}
      project_id_number: ${{ inputs.gcp-project-id }}

  - name: Pull latest image to scan
    shell: bash
    run: docker pull ${{ env.DOCKER_FULL_NAME }}

  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{env.DOCKER_FULL_NAME}}
      format: 'table'
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'
      trivyignores: ${{inputs.trivyignores}}
