name: 'Create SonarCloud Project If Needed'
description: 'Creates a SonarCloud project if it does not already exist.'
inputs:
  organization:
    description: 'The name of the SonarCloud organization'
    required: true
  repo-name:
    description: 'The name of the repository.'
    required: true
  sonar-token:
    description: 'The SonarCloud API token.'
    required: true
outputs:
  key:
    description: 'The key of the SonarCloud project.'
runs:
  using: 'node20'
  main: 'index.js'
