name: Update flake.lock

inputs:
  update_app_id:
    description: Key for the update app; try secrets.DEP_UPDATE_ID
    required: true
  update_app_key:
    description: Key for the update app; try secrets.DEP_UPDATE_KEY
    required: true

runs:
  using: composite
  steps:
  - name: Install Nix
    uses: cachix/install-nix-action@v17
    with:
      extra_nix_config: |
        access-tokens = github.com=${{ github.token }}
  - name: Get Updater Token
    uses: tibdex/github-app-token@v1
    id: generate-token
    with:
      app_id: ${{ inputs.update_app_id}}
      private_key: ${{inputs.update_app_key}}
  - name: Update flake.lock
    uses: nyarly/update-flake-lock@main # Open PR against upstream
    with:
      token: ${{ steps.generate-token.outputs.token }}
      commit-with-token: true
      pr-title: "Update flake.lock" # Title of PR to be created
      pr-labels: |                  # Labels to be set on the PR
        dependencies
        automated
      pr-body: |
        Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
        ```
        {{ env.GIT_COMMIT_MESSAGE }}
        ```
